name: flutter_plus
description: Create customized Containers/Buttons/TextFields/Texts/RichTexts in a few lines. Navigate between Screens and open BottomSheets/Dialogs/Snackbars without context and more!
version: 1.0.1
homepage: https://github.com/gbmiranda/flutter_plus.git
repository: https://github.com/gbmiranda/flutter_plus.git
issue_tracker: https://github.com/gbmiranda/flutter_plus/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  diacritic: ^0.1.3
  shared_preferences: ^2.0.6
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter: